import { Building } from './types';

export const BUILDINGS_DATA: Building[] = [
  {
    id: 'main_building',
    name: 'Main Building',
    icon: 'Building2',
    status: 'Active Operations',
    roomsCount: 9,
    coordinates: { x: 520, y: 247 },
    rooms: [
      {
        id: 'CR-A02',
        name: 'Room CR-A02 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free - Study Space',
        nextActivity: 'Financial Accounting II at 11:30 AM',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-A03',
        name: 'Room CR-A03 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Principles of Management (MGT-101)',
        nextActivity: 'Business Communication at 02:00 PM',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'CR-A07',
        name: 'Room CR-A07 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Introduction to Microeconomics (ECO-201)',
        nextActivity: 'Organizational Behavior at 03:30 PM',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 55,
      },
      {
        id: 'CR-A09',
        name: 'Room CR-A09 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free',
        nextActivity: 'Marketing Management at 04:00 PM',
        amenities: ['AC', 'Whiteboard'],
        capacity: 40,
      },
      {
        id: 'CR-A11',
        name: 'Room CR-A11 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'reserved',
        type: 'Lecture Hall',
        currentActivity: 'Departmental Seminar Setup',
        nextActivity: 'Alumni Meetup',
        amenities: ['AC', 'Projector', 'Smart Board'],
        capacity: 60,
      },
      {
        id: 'CR-A12',
        name: 'Room CR-A12 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Self Study Session',
        nextActivity: 'Strategic Management at 05:00 PM',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-A15',
        name: 'Room CR-A15 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Business Research Methods (MGT-411)',
        nextActivity: 'Free Study Space',
        amenities: ['AC', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'CR-A18',
        name: 'Room CR-A18 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free',
        nextActivity: 'Enterprise Resource Planning (ERP)',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'Main-Lab',
        name: 'Main Computer Laboratory',
        floor: 'Ground Floor',
        status: 'busy',
        type: 'Computer Lab',
        currentActivity: 'Management Information Systems Practical',
        nextActivity: 'Open Programming Hour',
        amenities: ['High-speed PCs', 'AC', 'Projector', 'Smart Board'],
        capacity: 60,
      }
    ]
  },
  {
    id: 'talpur_house',
    name: 'Talpur House',
    icon: 'Home',
    status: 'Academic Hub',
    roomsCount: 14,
    coordinates: { x: 200, y: 360 },
    rooms: [
      {
        id: 'CR-03',
        name: 'Room CR-03 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Basic Environmental Sciences',
        nextActivity: 'Biodiversity & Ecosystems',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-04',
        name: 'Room CR-04 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free',
        nextActivity: 'Climatology & Meteorology at 03:00 PM',
        amenities: ['AC', 'Whiteboard'],
        capacity: 40,
      },
      {
        id: 'Env-Lab',
        name: 'Environment Sciences Lab',
        floor: 'Ground Floor',
        status: 'busy',
        type: 'Computer Lab',
        currentActivity: 'Environmental Chemistry Practical',
        nextActivity: 'Soil and Water Quality Testing',
        amenities: ['Spectrophotometers', 'Water Sampling Kits', 'AC', 'Digital Boards'],
        capacity: 35,
      },
      {
        id: 'CR-101',
        name: 'Room CR-101 (Lecture Hall)',
        floor: 'First Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free Study Space',
        nextActivity: 'Discrete Structures at 02:30 PM',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'CR-102',
        name: 'Room CR-102 (Lecture Hall)',
        floor: 'First Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Digital Logic Design (CS-102)',
        nextActivity: 'Object Oriented Programming',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 55,
      },
      {
        id: 'CR-103',
        name: 'Room CR-103 (Lecture Hall)',
        floor: 'First Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free',
        nextActivity: 'Communication Skills (HU-102)',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-104',
        name: 'Room CR-104 (Lecture Hall)',
        floor: 'First Floor',
        status: 'reserved',
        type: 'Lecture Hall',
        currentActivity: 'Online Quiz Evaluation',
        nextActivity: 'Theory of Automata',
        amenities: ['AC', 'Projector', 'Smart Board'],
        capacity: 50,
      },
      {
        id: 'Comp-Lab-01',
        name: 'Computing Lab 1',
        floor: 'First Floor',
        status: 'busy',
        type: 'Computer Lab',
        currentActivity: 'Data Structures & Algorithms Practical',
        nextActivity: 'Software Engineering Lab Hours',
        amenities: ['Core-i7 Desktop PCs', 'AC', 'Projector', 'Smart Screen'],
        capacity: 45,
      },
      {
        id: 'Comp-Lab-02',
        name: 'Computing Lab 2',
        floor: 'First Floor',
        status: 'available',
        type: 'Computer Lab',
        currentActivity: 'Self Programming hours',
        nextActivity: 'Database Systems Lab (CS-311L)',
        amenities: ['Intel Development PCs', 'AC', 'High-Speed WiFi'],
        capacity: 40,
      },
      {
        id: 'CR-201',
        name: 'Room CR-201 (Lecture Hall)',
        floor: 'Second Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Artificial Intelligence Lecture',
        nextActivity: 'Design and Analysis of Algorithms',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'CR-202',
        name: 'Room CR-202 (Lecture Hall)',
        floor: 'Second Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free Study Hours',
        nextActivity: 'Compiler Construction at 04:00 PM',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-203',
        name: 'Room CR-203 (Lecture Hall)',
        floor: 'Second Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Professional Practices (CS-401)',
        nextActivity: 'Computer Networks lecture',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 55,
      },
      {
        id: 'CR-204',
        name: 'Room CR-204 (Lecture Hall)',
        floor: 'Second Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Independent Group Study',
        nextActivity: 'Cloud Computing Fundamentals',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'T-Comp-Lab',
        name: 'Talpur House General Computer Lab',
        floor: 'Second Floor',
        status: 'busy',
        type: 'Computer Lab',
        currentActivity: 'Visual Programming Laboratory (CS-302L)',
        nextActivity: 'Open Lab Session',
        amenities: ['Full Setup PCs', 'AC', 'Projector', 'Laser Printers'],
        capacity: 50,
      }
    ]
  },
  {
    id: 'auxiliary_building',
    name: 'Auxiliary Building',
    icon: 'Landmark',
    status: 'General Facilities',
    roomsCount: 13,
    coordinates: { x: 560, y: 315 },
    rooms: [
      {
        id: 'CR-401',
        name: 'Room CR-401 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Introduction to Sociology (HU-202)',
        nextActivity: 'Marketing Strategy & Ethics',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'CR-402',
        name: 'Room CR-402 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free Study Space',
        nextActivity: 'Macroeconomics lecture at 02:00 PM',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-403',
        name: 'Room CR-403 (Lecture Hall)',
        floor: 'Ground Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Organizational Theory (MGT-315)',
        nextActivity: 'Free Study Slot',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'CR-301',
        name: 'Room CR-301 (Lecture Hall)',
        floor: 'First Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free',
        nextActivity: 'Microeconomics I at 03:00 PM',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-302',
        name: 'Room CR-302 (Lecture Hall)',
        floor: 'First Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Financial Institutions & Markets',
        nextActivity: 'Commercial Law and Regulations',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'CR-303',
        name: 'Room CR-303 (Lecture Hall)',
        floor: 'First Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Self-Study Mode',
        nextActivity: 'Human Resource Management (HR-304)',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-304',
        name: 'Room CR-304 (Lecture Hall)',
        floor: 'First Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'International Business Management',
        nextActivity: 'Entrepreneurial Ventures',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'CR-305',
        name: 'Room CR-305 (Lecture Hall)',
        floor: 'First Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free',
        nextActivity: 'Operations Management at 04:30 PM',
        amenities: ['AC', 'Whiteboard'],
        capacity: 40,
      },
      {
        id: 'CR-306',
        name: 'Room CR-306 (Lecture Hall)',
        floor: 'First Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Consumer Behavior & Advertising',
        nextActivity: 'Digital Marketing Essentials',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 55,
      },
      {
        id: 'CR-307',
        name: 'Room CR-307 (Lecture Hall)',
        floor: 'First Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free',
        nextActivity: 'Business Research Seminar',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-404',
        name: 'Room CR-404 (Lecture Hall)',
        floor: 'First Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Supply Chain Logistics (MGT-460)',
        nextActivity: 'Procurement & Contract Management',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'CR-405',
        name: 'Room CR-405 (Lecture Hall)',
        floor: 'First Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free',
        nextActivity: 'Retail Management Strategy',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'CR-406',
        name: 'Room CR-406 (Lecture Hall)',
        floor: 'First Floor',
        status: 'reserved',
        type: 'Lecture Hall',
        currentActivity: 'Case Study Presentation Prep',
        nextActivity: 'Corporate Finance Guest Session',
        amenities: ['AC', 'Projector', 'Smart Panel'],
        capacity: 50,
      }
    ]
  },
  {
    id: 'it_tower',
    name: 'IT Tower',
    icon: 'Network',
    status: 'Lab & Servers',
    roomsCount: 16,
    coordinates: { x: 640, y: 90 },
    rooms: [
      {
        id: 'IT-Lab-201',
        name: 'IT Laboratory 201',
        floor: 'Second Floor',
        status: 'busy',
        type: 'Computer Lab',
        currentActivity: 'Web Programming Practical (CS-221L)',
        nextActivity: 'Mobile App Development Practical',
        amenities: ['Advanced Workstations', 'AC', 'Projector', '1G Ethernet'],
        capacity: 45,
      },
      {
        id: 'IT-Lab-202',
        name: 'IT Laboratory 202',
        floor: 'Second Floor',
        status: 'available',
        type: 'Computer Lab',
        currentActivity: 'Open Lab / Self-Study',
        nextActivity: 'Object-Oriented Web Lab',
        amenities: ['Dual Core PCs', 'AC', 'High-Speed WiFi'],
        capacity: 40,
      },
      {
        id: 'IT-Lab-203',
        name: 'IT Laboratory 203',
        floor: 'Second Floor',
        status: 'busy',
        type: 'Computer Lab',
        currentActivity: 'Database Administration Practical',
        nextActivity: 'Advanced Database Management',
        amenities: ['Linux Terminals', 'AC', 'Digital Screen'],
        capacity: 35,
      },
      {
        id: 'IT-Lab-204',
        name: 'IT Laboratory 204',
        floor: 'Second Floor',
        status: 'available',
        type: 'Computer Lab',
        currentActivity: 'Free Practice Slots',
        nextActivity: 'Human Computer Interaction Lab',
        amenities: ['Windows Workstations', 'AC'],
        capacity: 40,
      },
      {
        id: 'IT-301',
        name: 'Room IT-301 (Lecture Hall)',
        floor: 'Third Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Software Engineering Principles (CS-315)',
        nextActivity: 'Software Requirements & specs',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'IT-302',
        name: 'Room IT-302 (Lecture Hall)',
        floor: 'Third Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free Study Hour',
        nextActivity: 'Design Patterns Lecture at 03:00 PM',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'IT-303',
        name: 'Room IT-303 (Lecture Hall)',
        floor: 'Third Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Technical Writing & reporting',
        nextActivity: 'Professional Ethics (CS-402)',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'IT-304',
        name: 'Room IT-304 (Lecture Hall)',
        floor: 'Third Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free Study Session',
        nextActivity: 'Cloud Native Core Fundamentals',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'IT-401',
        name: 'Room IT-401 (Lecture Hall)',
        floor: 'Fourth Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Neural Networks & Deep Learning',
        nextActivity: 'Machine Learning Applications',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'IT-402',
        name: 'Room IT-402 (Lecture Hall)',
        floor: 'Fourth Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Independent Research Work',
        nextActivity: 'Computer Vision at 03:30 PM',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'IT-403',
        name: 'Room IT-403 (Lecture Hall)',
        floor: 'Fourth Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Natural Language Processing (CS-482)',
        nextActivity: 'Information Retrieval Systems',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 55,
      },
      {
        id: 'IT-404',
        name: 'Room IT-404 (Lecture Hall)',
        floor: 'Fourth Floor',
        status: 'reserved',
        type: 'Lecture Hall',
        currentActivity: 'AI Research Group Presentation',
        nextActivity: 'Data Analytics Workshop',
        amenities: ['AC', 'Projector', 'Smart Board'],
        capacity: 50,
      },
      {
        id: 'IT-501',
        name: 'Room IT-501 (Lecture Hall)',
        floor: 'Fifth Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Information Security Foundations',
        nextActivity: 'Cryptography and Protocols',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'IT-502',
        name: 'Room IT-502 (Lecture Hall)',
        floor: 'Fifth Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free',
        nextActivity: 'Ethical Hacking Lab Presentation',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      },
      {
        id: 'IT-503',
        name: 'Room IT-503 (Lecture Hall)',
        floor: 'Fifth Floor',
        status: 'busy',
        type: 'Lecture Hall',
        currentActivity: 'Computer Networks Security (CS-467)',
        nextActivity: 'Network Forensics & Audits',
        amenities: ['AC', 'Projector', 'Whiteboard'],
        capacity: 50,
      },
      {
        id: 'IT-504',
        name: 'Room IT-504 (Lecture Hall)',
        floor: 'Fifth Floor',
        status: 'available',
        type: 'Lecture Hall',
        currentActivity: 'Free Study Access',
        nextActivity: 'Distributed Systems Computing',
        amenities: ['AC', 'Whiteboard'],
        capacity: 45,
      }
    ]
  }
];

export const PATHS: Record<string, Record<string, { path: string, steps: string[] }>> = {
  main_building: {
    talpur_house: {
      path: 'M 520 247 L 400 290 L 200 360',
      steps: [
        'Exit the Main Building Ground Floor lobby.',
        'Walk Southwest along the central lawn brick pathway towards the Auxiliary Building (about 80 meters).',
        'Pass the Auxiliary Building and continue past the Academic Garden.',
        'Turn slightly Left, and enter the main entrance of Talpur House.'
      ]
    },
    auxiliary_building: {
      path: 'M 520 247 L 560 315',
      steps: [
        'Exit the Main Building South Wing.',
        'Walk directly Southeast across the fountain courtyard (about 30 meters).',
        'You will find Sir Shahnawaz Bhutto Auditorium entrance right in front of you at the Auxiliary Building.'
      ]
    },
    it_tower: {
      path: 'M 520 247 L 640 90',
      steps: [
        'Exit from the Main Building North Wing exit.',
        'Walk Northeast along the high-tech digital pathway (about 60 meters).',
        'The glass facade of the IT Tower will be straight ahead. Enter through the Security Turnstiles.'
      ]
    }
  },
  talpur_house: {
    main_building: {
      path: 'M 200 360 L 400 290 L 520 247',
      steps: [
        'Exit Talpur House main doors.',
        'Head Northeast along the central academic walkway.',
        'Continue path passing the Auxiliary Building on your right.',
        'Turn slightly Right and enter through the Main Building Grand Vault portal.'
      ]
    },
    auxiliary_building: {
      path: 'M 200 360 L 400 290 L 560 315',
      steps: [
        'Exit Talpur House.',
        'Walk Northeast towards the Central Library square.',
        'Turn Right near the Academic Garden and follow the signs towards Sir Shahnawaz Bhutto Auditorium.',
        'Auxiliary Building is right at the corner.'
      ]
    },
    it_tower: {
      path: 'M 200 360 L 400 290 L 520 247 L 640 90',
      steps: [
        'Exit Talpur House and walk along the Central Corridor.',
        'Cross the Main Lawn past the Auxiliary Building.',
        'Continue past the Main Building eastern wing.',
        'Proceed Northeast on the digital walkway to enter the IT Tower.'
      ]
    }
  },
  auxiliary_building: {
    main_building: {
      path: 'M 560 315 L 520 247',
      steps: [
        'Exit the Auxiliary Building main foyer.',
        'Cross the fountain plaza heading Northwest.',
        'Enter the Main Building via the southern entrance.'
      ]
    },
    talpur_house: {
      path: 'M 560 315 L 400 290 L 200 360',
      steps: [
        'Exit the Auxiliary Building.',
        'Head Northwest towards the Central Garden.',
        'Turn left onto the main campus paved road going Southwest.',
        'Follow it to the front gate of Talpur House.'
      ]
    },
    it_tower: {
      path: 'M 560 315 L 520 247 L 640 90',
      steps: [
        'Exit from the Auxiliary Building main doors.',
        'Head Northwest passing the Main Building lobby on your left.',
        'Keep heading Northeast along the high-tech pathway straight towards the IT Tower main entrance.'
      ]
    }
  },
  it_tower: {
    main_building: {
      path: 'M 640 90 L 520 247',
      steps: [
        'Exit the IT Tower modern lobby.',
        'Walk Southwest on the high-tech digital pathway.',
        'Pass the campus server farm on your right.',
        'Enter through the Main Building Northern Wing portal.'
      ]
    },
    talpur_house: {
      path: 'M 640 90 L 520 247 L 400 290 L 200 360',
      steps: [
        'Exit the IT Tower and walk Southwest past the Main Building.',
        'Cross the Lawn past the Auxiliary Building.',
        'Follow the central walkway heading down towards the Academic Garden.',
        'Enter Talpur House from the north gate.'
      ]
    },
    auxiliary_building: {
      path: 'M 640 90 L 520 247 L 560 315',
      steps: [
        'Exit the IT Tower modern foyer.',
        'Follow the digital corridor Southwest towards the Main Building North portal.',
        'Bypass the Main Building on the left, continuing towards the fountain square.',
        'The Auxiliary Building will be on your left.'
      ]
    }
  }
};
